services:
  web:
    build: .
    container_name: sustainify_web
    expose:
      - "80" # Expose port 80 to internal network only (no need to expose externally)
    volumes:
      - D:/Sustainify:/var/www/html # Mount the local directory to the web server container's directory
    depends_on:
      - sustainify_db
    networks:
      - sustainify_network

  sustainify_db:
    image: mysql:5.7
    container_name: sustainify_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: sustainify
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    ports:
      - "3306:3306" # Expose MySQL for phpMyAdmin
    networks:
      - sustainify_network

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: sustainify_db # Update the host to match the new database container name
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "8081:80" # Access phpMyAdmin on port 8081
    depends_on:
      - sustainify_db
    networks:
      - sustainify_network

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "80:80" # Expose port 80 to the host machine
    volumes:
      - D:/Sustainify/server/nginx.conf:/etc/nginx/nginx.conf # Mount custom Nginx config
    depends_on:
      - web
    networks:
      - sustainify_network

networks:
  sustainify_network:
    driver: bridge
